language: scala
sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.cache
    - $HOME/.sbt
    - $HOME/.ivy2/cache

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jobs:
  include:
    - stage: Compile
      script: sbt compile
    - stage: Style Check
      script: sbt headerCheck